### ISSUE TITLE
Add TIFF as an option?

### ISSUE THREAD

**Issue by droglenc** [jefferis/readbitmap#3]
Would be possible for you to easily add an option to identify and read in a TIFF file using `readTIFF()` from the `tiff` package ([here](https://cran.r-project.org/web/packages/tiff/tiff.pdf)). I could not figure out how the "magic numbers" are used in your `image_type()` function. Other than that it seems like the addition may be relatively straight-forward??

Thank you for considering this feature request.

**Comment by jefferis** [comment]
Happy to consider a patch. The TIFF magic bytes are

TIFF files begin with either II or MM followed by 42 as a two-byte integer in little or big endian byte ordering. II is for Intel, which uses little endian byte ordering, so the magic number is 49 49 2A 00. MM is for Motorola, which uses big endian byte ordering, so the magic number is 4D 4D 00 2A.

**Comment by droglenc** [comment]
I did look at [that](http://en.wikipedia.org/wiki/Magic_number_(programming)#Magic_numbers_in_files), but I could not figure it out. However, I missed the idea of converting hex to decimal. So, for JPEGs the wikipedia says:

> JPEG image files begin with FF D8 and end with FF D9. JPEG/JFIF files contain the ASCII code for "JFIF" (4A 46 49 46) as a null terminated string. JPEG/Exif files contain the ASCII code for "Exif" (45 78 69 66) also as a null terminated string, followed by more metadata about the file.

And your `image_type()` asks if the first two numbers are equal to 255 and 216 (the decimal equivalents to "FF" and "D8").

It looks like the decimal equivalents for the hex versions for PNG match up as well.

So, I just need to see if the first four numbers match 73 73 42 0 or 77 77 0 42 to determine if it is a TIFF. Does that sound about right?

I should have seen that. Sorry for troubling you with that. I will see if I can submit a patch to you sometime soon. Thank you for your help and consideration of this request.

**Comment by jefferis** [comment]
Closed by #4

**Comment by jefferis** [comment]
Thanks again!
