### ISSUE TITLE
Order of colour channels

### ISSUE THREAD

**Issue by dahtah** [jefferis/readbitmap#5]
It's just come to my attention that BMP stores colour channels in ARGB order, instead of the more usual (to me anyway) RGBA order. For consistency, I think it'd make sense for readbitmap to always return RGBA order, wouldn't it?

**Comment by dahtah** [comment]
Sure, I can give it a try.

**Comment by jefferis** [comment]
Closed by 2525df4ba2b3f61e0c316664f2bf758535d0066d. Thanks!
